#!/usr/bin/env node

var ABIManager = require("../abiManager");

async function main() {
    let crawler = new ABIManager();
    let abiStrArr = false
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            abiStrArr = val;
        }
    });
    if (abiStrArr){
      console.log(`loading`, abiStrArr)
      await crawler.load_abi(abiStrArr);
    }else{
      console.log(`cmd: loadabi [abiStrArr]`)
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
