#!/usr/bin/env node
 // Usage: ./writeBTHashesRealtime
var Manager = require("./manager");

async function main() {
    let manager = new Manager();
    let lookbackDays = 1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            lookbackDays = val;
        }
    });
    await manager.writeBTHashesRealtime(lookbackDays);
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
