#!/usr/bin/env node
 // Usage: 
// auditSubstrateETL polkadot 2021 2022-03-13

var SubstrateETL = require("./substrateetl");

async function main() {
    let relayChain = null;
    let paraID = -1;
    let logDT = null;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            relayChain = val;
        }
        if (index == 3 && val.length > 0) {
            paraID = parseInt(val, 10);
        }
        if (index == 4 && val.length > 0) {
            logDT = val;
        }
    });

    var substrateetl = new SubstrateETL();
    if (paraID >= 0 && logDT && relayChain) {
        await substrateetl.audit_substrateetl(logDT, paraID, relayChain);
    } else {
	await substrateetl.audit_random_substrateetl();
    }
}

main()
    .then(() => {
        console.log("finishing...")
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
