#!/usr/bin/env node
/*
 Usage: checkRoutes [symbol]
*/

var PriceManager = require("./priceManager");
var ParaTool = require("./paraTool");

async function main() {
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = val;
	}
    });
    var priceManager = new PriceManager();

    await priceManager.checkRoutes(chainID);
}

main()
    .then(() => {
	process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
