#!/usr/bin/env node
 // Usage:  crawlEVMTraces [chainID]

var Crawler = require("./crawler");
async function main() {
    var chainID = -1;
    var crawler = new Crawler();
    let n = 0;
    let nmax = 1;
    await crawler.assetManagerInit();
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
        if (index == 3 && val.length > 0) {
            n = parseInt(val, 10);
        }
        if (index == 4 && val.length > 0) {
            nmax = parseInt(val, 10);
        }
    });
    if (chainID >= 0) {
        await crawler.crawlTracesEVM(chainID, ["mod", n, nmax]);
    } else {
	do {
            await crawler.crawlTracesRandom();
	    await crawler.sleep(5000);
	} while (true );
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
