#!/usr/bin/env node
 // Usage: crawlBackfill chainID
var Crawler = require("./crawler");

async function main() {
    let chainID = -1;
    let n = 0;
    let nmax = 1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
        if (index == 3 && val.length > 0) {
            n = parseInt(val, 10);
        }
        if (index == 4 && val.length > 0) {
            nmax = parseInt(val, 10);
        }
    });

    var crawler = new Crawler();
    await crawler.assetManagerInit();
    var chain = await crawler.getChain(chainID);
    await crawler.crawlBackfill(chain, ["mod", n, nmax], true);
    await crawler.release();
}

main()
    .then(() => process.exit(0))
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
