#!/usr/bin/env node

const {
    Command
} = require('commander');
var EVMETL = require("./evmetl");

function myParseInt(value, dummyPrevious) {
    const parsedValue = parseInt(value, 10);
    if (isNaN(parsedValue)) {
        throw new commander.InvalidArgumentError('Not a number.');
    }
    return parsedValue;
}

async function main() {
    let cli_version = '0.1.0'
    const program = new Command();
    program
        .name('evm-etl')
        .description('Manage polkaholic export to BigQuery substrate-etl project')
        .version(`${cli_version}`);

    program.command('crawlabi')
        .description(`Get ABI for contract from external API (Etherscan, ...) based on chainID`)
        .option('-c, --chainID <chainID>', 'ChainID to update balances', myParseInt, 1)
        .option('-p, --project <project>', 'Project Name (e.g. wormhole)', "")
        .option('-n, --contractName <contractName>', 'Contract Name (e.g. Endpoint)', "")
        .argument('<address>', 'Contract Address')
        .action(async (address, opt) => {
            let chainID = opt.chainID != null ? opt.chainID : 1;
            let project = opt.project ? opt.project : null;
            let contractName = opt.contractName ? opt.contractName : null;
            let evmetl = new EVMETL();
            await evmetl.crawlABI(address, chainID, project, contractName);
            process.exit(0);
        });

    program.command('generateproject')
        .description(`Get ABI for contract from external API (Etherscan, ...) based on chainID`)
        .option('-c, --chainID <chainID>', 'ChainID to update balances', myParseInt, 1)
        .option('-p, --project <project>', 'Project Name (e.g. wormhole)', "")
        .option('-n, --contractName <contractName>', 'Contract Name (e.g. Endpoint)', "")
        .argument('<address>', 'Contract Address')
        .action(async (address, opt) => {
            let chainID = opt.chainID != null ? opt.chainID : 1;
            let project = opt.project ? opt.project : null;
            let contractName = opt.contractName ? opt.contractName : null;
            let evmetl = new EVMETL();
            await evmetl.initEvmSchemaMap()
            await evmetl.generateProject(address, chainID, project, contractName);
            process.exit(0);
        });

    program.command('crawlabis')
        .description(`Get New ABIs`)
        .option('-c, --chainID <chainID>', 'ChainID to crawl ABIs', myParseInt, null)
        .action(async (opt) => {
            console.log(opt);
            let evmetl = new EVMETL();
            await evmetl.crawlABIs(opt.chainID);
            process.exit(0);
        });

    program.command('loadabi')
        .description(`Get ABI for contract`)
        .argument('<abistr>', 'Contract Address')
        .action(async (abistr, opt) => {
            let evmetl = new EVMETL();
            await evmetl.loadABI(abistr);
            process.exit(0);
        });

    program.command('loadabirepo')
        .description(`Load ABI Repo into BigQuery`)
        .action(async (abistr, opt) => {
            let evmetl = new EVMETL();
            await evmetl.loadABIRepo();
            process.exit(0);
        });

    program.command('asset_platforms')
        .description(`Fetch Asset Platforms (from coingecko)`)
        .action(async (opt) => {
            var PriceManager = require("./priceManager");
            let pm = new PriceManager();
            await pm.update_coingecko_asset_platforms();
            process.exit(0);
        });

    program.command('priceusd')
        .description(`Fetch Price USD (from coingecko)`)
        .action(async (opt) => {
            var PriceManager = require("./priceManager");
            let pm = new PriceManager();
            await pm.update_coingecko_token_price_usd();
            process.exit(0);
        });

    program.command('addcontracttype')
        .description(`Add Contract Type ABI for contract`)
        .argument('<contractType>', 'Contract Address')
        .argument('<abistr>', 'Contract Address')
        .action(async (contractType, abistr, opt) => {
            let evmetl = new EVMETL();
            await evmetl.addContractType(contractType, abistr);
            process.exit(0);
        });

    program.command('contracttypes')
        .description(`Update Contract Types`)
        .action(async (opt) => {
            console.log(opt);
            let evmetl = new EVMETL();
            await evmetl.updateContractTypes(opt.chainID);
            process.exit(0);
        });

    program.command('reloadabi')
        .description(`Reload ABI`)
        .option('-s, --sql <targetSQL>', 'Target SQL', null)
        .action(async (abistr, opt) => {
            let evmetl = new EVMETL();
            await evmetl.reloadABI(opt.sql);
            process.exit(0);
        });

    program.command('setupevm')
        .description("Setup or update BigQuery tables for EVM Chain. Use -u to update tbl schema")
        .usage("-c 137")
        .option('-c, --chainID <chainID>', 'ChainID', null)
        .option('-u, --update', `update schema mode`, false)
        .action(async (opt) => {
            var substrateetl = new SubstrateETL();
            let chainID = opt.chainID
            let isUpdate = (opt.update) ? true : false
            let isAll = (opt.all) ? true : false
            if (chainID != undefined) chainID = myParseInt(chainID)
            await evmetl.setup_chain_evm(chainID, isUpdate);
            process.exit(0);
        })


    program.command('setupdataset')
        .description("Setup dataset in substrate-etl")
        .usage("-d evm_dev")
        .option('-d, --datasetID <datasetID>', 'datasetID', 'evm_dev')
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let datasetID = opt.datasetID
            await evmetl.setup_dataset(datasetID);
            process.exit(0);
        })

    program.command('deletedataset')
        .description("Delete dataset in substrate-etl")
        .usage("-d evm_dev")
        .option('-d, --datasetID <datasetID>', 'datasetID', 'evm_dev')
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let datasetID = opt.datasetID
            await evmetl.delete_dataset(datasetID);
            process.exit(0);
        })

    program.command('abianalytics')
        .description(`Reload ABIs`)
        .action(async (abistr, opt) => {
            let evmetl = new EVMETL();
            await evmetl.abiAnalytics();
            process.exit(0);
        });

    program.command('callevents')
        .description(`Generate schemas for calls+events`)
        .option('-c, --create', `crate table schema mode`, false)
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let isCreate = (opt.create) ? true : false
            await evmetl.setupCallEvents(isCreate);
            process.exit(0);
        });

    program.command('loadlabels')
        .argument('<chainID>', 'Address')
        .argument('<fileName>', `Storage Slot`)
        .action(async (chainID, fileName, opt) => {
            var evmetl = new EVMETL();
            await evmetl.loadLabels(chainID, fileName);
            process.exit(0);
        });

    program.command('getStorageAt')
        .description(`run getStorageAt`)
        .argument('<address>', 'Address')
        .argument('<storageSlot>', `Storage Slot`)
        .option('-c, --chainID <chainID>', 'Address', 1)
        .action(async (address, storageSlot, opt) => {
            var evmetl = new EVMETL();
            let res = await evmetl.getStorageAt(storageSlot, address, opt.chainID);
            console.log(res);
            process.exit(0);
        });

    program.command('projects')
        .action(async (address, storageSlot, opt) => {
            var evmetl = new EVMETL();
            await evmetl.modelProjects();
            process.exit(0);
        });

    program.command('project')
        .option('-a, --abiType <abiType>', "event")
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let abiType = opt.abiType ? opt.abiType : "event";
            await evmetl.enrich_projectcontractabi(abiType);
            process.exit(0);
        });


    program.command('dryrun')
        .argument('<query>', `Query`)
        .action(async (query) => {
            var evmetl = new EVMETL();
            await evmetl.dryrun(query);
            process.exit(0);
        });

    program.command('projectschema')
        .option('-d, --datasetId <datasetId>', "Model datasetID", null)
        .option('-p, --project <projectId>', "Model project", null)
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let datasetId = opt.datasetId ? opt.datasetId : null;
            let projectId = opt.projectId ? opt.projectId : "blockchain-etl";
            await evmetl.load_project_schema(datasetId, projectId);
            process.exit(0);
        });

    program.command('projectroutines')
        .option('-d, --datasetId <datasetId>', "Model datasetID", null)
        .option('-p, --project <projectId>', "Model project", null)
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let datasetId = opt.datasetId ? opt.datasetId : null;
            let projectId = opt.projectId ? opt.projectId : "blockchain-etl-internal";
            await evmetl.load_project_routines(datasetId, projectId);
            process.exit(0);
        });

    program.command('blcp')
        .option('-c', 1, null)
        .option('-l, --logDT <logDT>', 'Date', null)
        .option('-e, --endDT <endDT>', 'For multi-day ranges', null)
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let chainID = opt.chainID ? opt.chainID : 1;
            let logDT = opt.logDT ? opt.logDT : "2023-04-01";
            let endDT = opt.logDT && opt.endDT ? opt.endDT : null;
            if (logDT) {
                if (endDT) {
                    let logDTRange = evmetl.getLogDTRange(logDT, endDT)
                    for (const dt of logDTRange) {
                        await evmetl.blcp(dt, chainID);
                    }
                } else {
                    await evmetl.blcp(logDT, chainID);
                }
            }

            process.exit(0);
        });

    program.command('backfill')
        .option('-c', 1, null)
        .option('-l, --logDT <logDT>', 'Date', null)
        .option('-e, --endDT <endDT>', 'For multi-day ranges', null)
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let chainID = opt.chainID ? opt.chainID : 1;
            let logDT = opt.logDT ? opt.logDT : "2023-04-01";
            let endDT = opt.logDT && opt.endDT ? opt.endDT : null;
            if (logDT) {
                if (endDT) {
                    let logDTRange = evmetl.getLogDTRange(logDT, endDT)
                    for (const dt of logDTRange) {
                        await evmetl.backfill(dt, chainID);
                    }
                } else {
                    await evmetl.backfill(logDT, chainID);
                }
            }
            process.exit(0);
        });

    program.command('indexchain')
        .option('-c', 1, null)
        .option('-l, --logDT <logDT>', 'Date', null)
        .option('-e, --endDT <endDT>', 'For multi-day ranges', null)
        .action(async (opt) => {
            var evmetl = new EVMETL();
            let chainID = opt.chainID ? opt.chainID : 1;
            let logDT = opt.logDT ? opt.logDT : "2023-04-01";
            let endDT = opt.logDT && opt.endDT ? opt.endDT : null;
            if (logDT) {
                if (endDT) {
                    let logDTRange = evmetl.getLogDTRange(logDT, endDT)
                    for (const dt of logDTRange) {
                        await evmetl.index_evmchain(chainID, dt);
                    }
                } else {
                    await evmetl.index_evmchain(chainID, logDT);
                }
            }
            process.exit(0);
        });


    await program.parseAsync(process.argv);
}

main()
    .then(() => {
        // do not process.exit(0) here
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    })
