#!/usr/bin/env node

var PriceManager = require("./priceManager");

function    date_key_to_ts(datekey = "2021-12-21") {
    let logDT = datekey.replaceAll('-', "")
    var y = logDT.substr(0, 4),
        m = logDT.substr(4, 2),
        d = logDT.substr(6, 2)
    let a = new Date(`${y}-${m}-${d}`)
    let logDTTS = a.getTime() / 1000;
    return logDTTS
}

async function main() {
    let manager = new PriceManager();
    await manager.init();
    let startTS = date_key_to_ts("20211001");
    let endTS = Math.round(new Date().getTime() / 1000)
    let lookback = 1;
    let run = false;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            startTS = date_key_to_ts(val);
        }
        if (index == 3 && val.length > 0) {
            endTS = date_key_to_ts(val);
	    run = true;
        }
    });
    if ( run ) {
	await manager.getCoinPricesRange(startTS, endTS);
	//await manager.getCoinPrices(7);
    } else {
	await manager.getCoinPrices(0);
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
