#!/usr/bin/env node

var Crawler = require("./crawler");
var paraTool = require("./paraTool");

async function main() {
    let crawler = new Crawler();
    crawler.setDebugLevel(paraTool.debugErrorOnly)
    let chainID = false;
    let n = 0;
    let nmax = 1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
        if (index == 3 && val.length > 0) {
            n = parseInt(val, 10);
        }
        if (index == 4 && val.length > 0) {
            nmax = parseInt(val, 10);
        }
    });
    let chain = await crawler.getChain(chainID);
    await crawler.assetManagerInit();
    crawler.exitOnDisconnect = true;

    await crawler.indexChain(chain, 60, false, false, true, ["mod", n, nmax]);
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
