#!/usr/bin/env node
// Usage: while true; do ./indexChain 10; done

var Crawler = require("./crawler");
async function main() {
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = val;
        }
    });

    if ( chainID >= 0 ) {
       let crawler = new Crawler();
       let chain = await crawler.getChain(chainID);
       await crawler.indexChain(chain, 60, true, true);
       await crawler.sleep(3*1000);
    } else {
	do {
	    let crawler = new Crawler();
	    await crawler.assetManagerInit();
	    let indexed = await crawler.indexChainRandom();
	    if ( indexed ) {
		await crawler.release(3*1000);
	    } else {
		await crawler.release(20*1000);
	    }
	} while ( true ) ;
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
