#!/usr/bin/env node
/*
 Usage: showAssetCycles [symbol]
*/

var PriceManager = require("./priceManager");
var ParaTool = require("./paraTool");

async function main() {
    let symbol = null;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            symbol = val;
	}
    });
    var priceManager = new PriceManager();
    await priceManager.showAssetCycles(symbol);
}

main()
    .then(() => {
	process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
