#!/usr/bin/env node
// Usage: ./updateXCMTransfer

var AssetManager = require("./assetManager");

async function main() {
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = val;
        }
    });
    var assetManager = new AssetManager();
    await assetManager.assetManagerInit();
    await assetManager.updateXCMTransfer();
}

main()
    .then(() => {
	process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
