#!/usr/bin/env node
/*
 Usage: checkRoutes [symbol]
*/

var PriceManager = require("./priceManager");
var ParaTool = require("./paraTool");

async function main() {
    let chainID = 2000;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
	    chainID = parseInt(val, 10);
        }
    });
    var priceManager = new PriceManager();
    await priceManager.assetpricelogGenerationParachain(chainID);
    //await priceManager.updateAssetPriceLog(chainID);
}

main()
    .then(() => {
	process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
