#!/usr/bin/env node
 // Usage:  updateAddressBalances
var Manager = require("./manager");
async function main() {
    var manager = new Manager();
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
    });
    await manager.updateChainlogNumAccountsActive(chainID);
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
