#!/usr/bin/env node
/*
 Usage: updateAssetPriceLog [chainID]
*/

var PriceManager = require("./priceManager");
var ParaTool = require("./paraTool");

async function main() {
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
	    chainID = parseInt(val, 10);
        }
    });
    if ( chainID == -1 ) {
	let chainIDs = [2006, 2004];
	let priceManager = new PriceManager();
	for ( const chainID of chainIDs) {
	    await priceManager.updateAssetPriceLog(chainID, "latest");
	}
	await priceManager.computeBestCrossChainPriceUSD();
    } else {
	let priceManager = new PriceManager();
	await priceManager.updateAssetPriceLog(chainID);
	await priceManager.computeBestCrossChainPriceUSD();
    }
}

main()
    .then(() => {
	process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
