#!/usr/bin/env node
 // Usage:  updateAddressBalances
var SubstrateETL = require("./substrateetl");
async function main() {
    var manager = new SubstrateETL();
    let chainID = -1;
    let logDT = null;
    
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
        if (index == 3 && val.length > 0) {
            logDT = val;
        }
    });
    if ( logDT ) {
	await manager.updateBlocklog(chainID, logDT);
    } else if ( chainID ) {
	await manager.updateBlocklogBulk(chainID);
    } else {
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
