#!/usr/bin/env node
 // Usage:  updateAddressBalances
var SubstrateETL = require("./substrateetl");
var paraTool = require("./paraTool");
async function main() {
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
    });
    if ( chainID >= 0 ) {
	var manager = new SubstrateETL();
	let done = false;
	do {
	    done = await manager.update_address_balances_logDT(chainID);
	} while ( ! done ) 
    } else {
	while ( 1 ) {
	    var manager = new SubstrateETL();
	    let res = await manager.updateAddressBalances();
	    if ( res == false ) {
		await manager.sleep(30000);
	    } else {
		await manager.sleep(5000);
	    }
	}
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
