#!/usr/bin/env node
 // Usage:  updateIndexlogBlocknumberNewSession
var Manager = require("./manager");
async function main() {
    var manager = new Manager();
    await manager.updateIndexlogBlocknumberNewSession();
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
