#!/usr/bin/env node
 // Usage: while true; do ./indexChain 10; done
var Crawler = require("./crawler");

async function main() {
    let chainID = -1;
    let daysago = 365;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = val;
        }
        if (index == 3 && val.length > 0) {
            daysago = val;
        }
    });
    if ( chainID >= 0 ) {
       let crawler = new Crawler();
	crawler.exitOnDisconnect = true;
	let chain = await crawler.getChain(chainID);
	await crawler.updateChainAssets(chainID, daysago);
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
