#!/usr/bin/env node
 // Usage:  updateAddressBalances
var Manager = require("./manager");
var paraTool = require("./paraTool");
async function main() {
    var manager = new Manager();
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = parseInt(val, 10);
        }
    });
    if ( chainID >= 0 ) {
	let ts = manager.getCurrentTS() - 86400;
	console.log("TS", ts);
	let [logDT, hr] = paraTool.ts_to_logDT_hr(ts)
	manager.clean_bqlogfn(chainID, logDT);
	await manager.updateNativeBalances(chainID, logDT);
	await manager.updateNonNativeBalances(chainID, logDT);
	await manager.update_chain_lastBalanceUpdateDT(chainID);
	manager.load_bqlogfn(chainID, logDT);
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
