#!/usr/bin/env node
 // Usage:  updateSpecVersions [chainID]
const endpoints = require("./summary/endpoints");

var Crawler = require("./crawler");
async function main() {
    let chainID = -1;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            chainID = val;
        }
    });
    if (chainID >= 0) {
        var crawler = new Crawler();
        await crawler.updateChainAssets(chainID, 100);
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
