#!/usr/bin/env node
// Usage:  updateBQLog [logDT]
// if no date supplied, uses yesterday

var Manager = require("./manager");
var paraTool = require("./paraTool");

async function main() {
    var manager = new Manager();
    let startts = manager.getCurrentTS() - 86400;
    let [startDT, _] = paraTool.ts_to_logDT_hr(startts);
    let endts = manager.getCurrentTS();
    let [endDT, __] = paraTool.ts_to_logDT_hr(endts);
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            startDT = val;
        }
        if (index == 3 && val.length > 0) {
            endDT = val;
        }
    });
    console.log("updateBQLog: ", startDT, "to", endDT);
    await manager.updateBQLog(startDT, endDT);
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
