#!/usr/bin/env node
 // Usage:  xcmcleaner [extrinsicHash]
var XCMCleaner = require("./xcmCleaner.js");

async function main() {
    let extrinsicHash = null;
    process.argv.forEach(function(val, index, array) {
      if (index == 2 && val.length > 0) {
        extrinsicHash = val;
      }
    });
    if ( extrinsicHash ) {
	var manager = new XCMCleaner();
	await manager.assetManagerInit();
	if ( extrinsicHash.length > 10 ) {
	    await manager.cleanXCMInfo(extrinsicHash, transferIndex, xcmIndex);
	} else {
	    await manager.bulk_generate_XCMInfo(extrinsicHash, 1000);
	}
    } else {
	var manager = new XCMCleaner();
	await manager.assetManagerInit();
	await manager.bulk_generate_XCMInfo(null, 1);
    }
}


main()
    .then(() => {
        console.log("finishing...")

        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
