#!/usr/bin/env node
 // Usage:  xcmcleaner [extrinsicHash]
var XCMCleaner = require("./xcmCleaner.js");

async function main() {
    let extrinsicHash = "22110";
    let xcmIndex = 0;
    let transferIndex = 0;
    process.argv.forEach(function(val, index, array) {
      if (index == 2 && val.length > 0) {
        extrinsicHash = val;
      }
      if (index == 3 && val.length > 0) {
        transferIndex = parseInt(val, 10);
      }
      if (index == 4 && val.length > 0) {
        xcmIndex = parseInt(val, 10);
      }
    });
    var manager = new XCMCleaner();
    await manager.assetManagerInit();
    if ( extrinsicHash.length > 10 ) {
	await manager.cleanXCMInfo(extrinsicHash, transferIndex, xcmIndex);
    } else {
	await manager.bulk_cleanXCMInfo(extrinsicHash)
    }
}


main()
    .then(() => {
        console.log("finishing...")

        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
