#!/usr/bin/env node
 // Usage:  xcmmatch [lookbackDays] [rematch]
var XCMManager = require("./xcmmanager");

async function main() {
    let limit = 1000;
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            limit = parseInt(val, 10);
        }
    });
    let isNotDone = true
    let lastUpdateTS = 0;
    var manager = new XCMManager();
    manager.init_xcm_error_map();
    await manager.xcm_init()
    await manager.assetManagerInit();
    let chain = await manager.getChain(2);
    await manager.setupAPI(chain);
    do {
        // startTS that comes back is the last message unix timestamp
        isNotDone = await manager.auditMsgHash(limit);
    } while (isNotDone);
}


main()
    .then(() => {
        console.log("finishing...")

        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
