#!/usr/bin/env node
 // Usage: xcmTrace trace.json
const fs = require('fs');
const paraTool = require("./paraTool");
const AssetManager = require("./assetManager");
const events = require('events');
const readline = require('readline');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

class XCMTracer extends AssetManager {
    xcm = {};
    extrinsic = {};
    dest = {};
    spans = {};
    remoteexecution = {};

    idhash(id) {
        return paraTool.twox_128("GB" + id).substring(0, 16);
    }
    getInstructionSet() {
        let instructionSet = {
            'withdrawAsset': { // Remove the on-chain asset(s) (assets) and accrue them into Holding
                MultiAssets: ['assets'],
                MultiAssetFilter: ['assets'], //v0
                Effects: ['effects'] //v0
            },
            'reserveAssetDeposited': { // Accrue into Holding derivative assets to represent the asset(s) (assets) on Origin.
                MultiAssets: ['assets']
            },
            'receiveTeleportedAsset': {
                MultiAssets: ['assets']
            },
            'queryResponse': {},
            'transferAsset': {
                MultiAssetFilter: ['assets'],
                MultiLocation: ['beneficiary'],
            },
            'transferReserveAsset': {
                MultiAsset: ['assets'],
                MultiLocation: ['destination'],
                XCM: ['xcm']
            },
            'transact': {
                Call: ['call']
            },
            'hrmpNewChannelOpenRequest': {},
            'hrmpChannelAccepted': {},
            'hrmpChannelClosing': {},
            'clearOrigin': {},
            'descendOrigin': {},
            'reportError': {},
            'depositAsset': { // Subtract the asset(s) (assets) from Holding and deposit on-chain equivalent assets under the ownership of beneficiary.
                MultiAssetFilter: ['assets'],
                MultiLocation: ['beneficiary']
            },
            'depositReserveAsset': {
                MultiAssetFilter: ['assets'],
                MultiLocation: ['beneficiary'],
                XCM: ['xcm']
            },
            'exchangeAsset': {
                MultiAssetFilter: ['give'],
                MultiAssets: ['receive']
            },
            'initiateReserveWithdraw': {
                MultiAssetFilter: ['assets'],
                XCM: ['xcm']
            },
            'initiateTeleport': {
                MultiAssetFilter: ['assets'],
                MultiLocation: ['destination'],
                XCM: ['xcm']
            },
            'queryHolding': {
                MultiLocation: ['destination'],
                MultiAssetFilter: ['assets']
            },
            'buyExecution': { //Pay for the execution of the current message from Holding.
                MultiAsset: ['fees']
            },
            'refundSurplus': {},
            'setErrorHandler': {},
            'setAppendix': {},
            'clearError': {},
            'claimAsset': {
                MultiAsset: ['assets'],
                MultiLocation: ['ticket']
            },
            'trap': {},
            'subscribeVersion': {},
            'unsubscribeVersion': {},
            'burnAsset': {
                MultiAsset: ['assets']
            },
            'expectAsset': {
                MultiAsset: ['assets']
            },
            'expectOrigin': {
                MultiLocation: ['origin']
            },
            'expectError': {},
            //V1
            'reserveAssetDeposited': {
                MultiAssetFilter: ['assets'],
                Effects: ['effects'],
            },
            //V0
            'teleportAsset': {
                MultiAsset: ['assets'],
                Effects: ['effects'],
            },
            'reserveAssetDeposit': {
                MultiAsset: ['assets'],
                Effects: ['effects'],
            }
        }
        return instructionSet
    }

    // maps dest like "{ parents: 0, interior: { x1: { parachain: 2000 } } }" into just "2000"
    dest_to_chainID(dest, relayChain = "polkadot") {
        if (dest && dest.interior && dest.interior.x1 && dest.interior.x1.parachain) {
            let paraID = dest.interior.x1.parachain;
            return (paraTool.getChainIDFromParaIDAndRelayChain(paraID, relayChain));
        }
        return (null)
    }

    async submitleg(extrinsicID, ext, msgHash, destEventID, parentspanid = null, chainIDDest = null) {
        let traceId = this.idhash(extrinsicID);
        let sectionMethod = "extrinsic";
        let id = "origination"
        let idDest = "destination";
        if (ext) {
            let exttags = {};
            let chainID = ext.chainID;
            let chainIDDest = ext.chainIDDest;
            let [__, _id] = this.getNameByChainID(ext.chainID)
            let [_, _idDest] = this.getNameByChainID(ext.chainIDDest)
            id = _id;
            idDest = _idDest;
            for (const [k, v] of Object.entries(ext)) {
                switch (k) {
                    case "chainID":
                    case "chainIDDest":
                    case "incomplete":
                    case "isFeeItem":
                    case "msgHash":
                    case "relayChain":
                    case "xcmIndex":
                    case "transferIndex":
                    case "sourceTS":
                    case "sentAt":
                    case "xcmType":
                        break;
                    case "amountSent":
                        exttags[k.toString()] = v.toString();
                        let p = await this.computePriceUSD({
                            symbol: ext.xcmSymbol,
                            relayChain: ext.relayChain,
                            ts: ext.sourceTS
                        });
                        if (p) {
                            exttags[`amountSentRaw`] = ext.amountSent.toString();
                            exttags[`amountSent`] = `${ext.amountSent/10**p.assetInfo.decimals} ${ext.xcmSymbol}`;
                            exttags["amountSentUSD"] = (p.priceUSD * ext.amountSent / 10 ** p.assetInfo.decimals).toString();
                        }
                        break;
                    case "extrinsicHash":
                        exttags[k.toString()] = v.toString();
                        exttags["extrinsicURL"] = `https://polkaholic.io/extrinsic/${v}`
                        break;
                    case "blockNumber":
                        exttags[k.toString()] = v.toString();
                        exttags["blockNumberURL"] = `https://polkaholic.io/block/${id}/${v}`
                        break;
                    case "sectionMethod":
                        sectionMethod = v.toString();
                        break;
                    default:
                        exttags[k.toString()] = v.toString();
                }
            }

            this.push_span(extrinsicID, {
                id: traceId,
                traceId: traceId,
                timestamp: ext.sourceTS * 1000000,
                duration: 1000000,
                name: sectionMethod,
                tags: exttags,
                localEndpoint: {
                    serviceName: id
                }
            })
            if (parentspanid == null) {
                parentspanid = traceId;
            }
        } else {
            if (chainIDDest != null) {
                try {
                    let [_, _idDest] = this.getNameByChainID(chainIDDest)
                    idDest = _idDest;
                } catch (err) {
                    console.log("this.getNameByChainID FAIL0", chainIDDest);
                }
            }
        }

        let xcm = this.xcm[msgHash];
        let xcmid = this.idhash(msgHash);
        let msgtags = {}
        let msgType = "xcmp";
        let msgHex = null;
        let prevspanid = parentspanid;
        if (xcm) {
            for (const [k, v] of Object.entries(xcm)) {
                if (v) {
                    let k0 = k.toString();
                    let v0 = v.toString();
                    switch (k) {
                        case "msgType":
                            msgType = v.toString();
                            // messages processed on relay chain
                            if (msgType == "ump") {
                                idDest = xcm.relayChain
                            } else {
                                try {
                                    let [_chainID, _idDest] = this.getNameByChainID(xcm.chainIDDest.toString())
                                    idDest = _idDest;
                                    chainIDDest = _chainID;

                                } catch (err) {
                                    console.log(err)
                                    console.log("this.getNameByChainID FAIL1", xcm.chainIDDest, JSON.stringify(Object.keys(this.chainInfos)));
                                    process.exit(0);
                                }
                            }
                            break;
                        case "instructions":
                        case "blockTS":
                        case "chainID":
                        case "chainIDDest":
                        case "isIncoming":
                        case "relayChain":
                            break;
                        case "msgHex":
                            msgHex = xcm.msgHex;
                            break;
                        case "msgStr":
                            //let xcm = JSON.parse(v0);
                            msgtags[k0] = v0;
                            break;
                        default:
                            msgtags[k0] = v0;
                    }
                }
            }
            this.push_span(extrinsicID, {
                id: xcmid,
                traceId: traceId,
                timestamp: xcm.blockTS * 1000000,
                duration: 1000000,
                name: `xcm:${msgType}`,
                parentId: prevspanid,
                tags: msgtags,
                localEndpoint: {
                    serviceName: xcm.relayChain
                }
            })
            prevspanid = xcmid;
            if (xcm.instructions) {
                // the xcm message received by the dest may result in one or more legs
                //   in receive_msg, we precomputed which instructions actually have recursive xcm instructions inside them
                let ts = xcm.blockTS * 1000000;

                for (let i = 0; i < xcm.instructions.length; i++) {
                    let {
                        instruction,
                        hex,
                        childinstruction,
                        childhex
                    } = xcm.instructions[i];
                    let spanid = this.idhash(prevspanid + hex);
                    let [opcode, params] = this.get_instruction_opcode_params(xcm.instructions[i].instruction.toJSON());
                    let ms = 1000; // TODO: put weight here instead
                    let instructiontags = {
                        "hex": xcm.instructions[i].hex
                    };
                    let requireWeightAtMost = 8000000000;
                    if (params) {
                        if (Array.isArray(params)) {
                            instructiontags["params"] = JSON.stringify(params)
                        } else if (typeof params === 'object') {
                            for (const [k, v] of Object.entries(params)) {
                                if (v) {
                                    switch (k) {
                                        case "requireWeightAtMost":
                                            requireWeightAtMost = v;
                                            break;
                                    }
                                }
                                instructiontags[k] = JSON.stringify(v);
                            }
                        }
                    }
                    this.push_span(extrinsicID, {
                        id: spanid,
                        parentId: prevspanid,
                        traceId: traceId,
                        timestamp: ts,
                        duration: ms,
                        name: `xcvm:${opcode}`,
                        tags: instructiontags,
                        localEndpoint: {
                            serviceName: idDest // this is the parachain executing the instruction -- compute it using "dest" multilocation
                        }
                    })
                    ts += ms;
                    ts++;
                    prevspanid = spanid;

                    if (msgHash && opcode == "transact" && (this.remoteexecution[msgHash] != undefined)) {
                        let remoteexecution = this.remoteexecution[msgHash];
                        let remoteexecutiontags = {}
                        let remoteexecutionts = ts;
                        let childextrinsicID = null;
                        for (const [k, v] of Object.entries(remoteexecution)) {
                            if (v) {
                                let k0 = k.toString();
                                let v0 = v.toString();
                                switch (k) {
                                    case "chainID":
                                    case "msgHash":
                                    case "isConnectedCall":
                                        break;
                                    case "timestamp":
                                        remoteexecutionts = v * 1000000;
                                        break;
                                    case "swaps":
                                    case "transfers":
                                    case "accessList":
                                        if (Array.isArray(v) && v.length > 0) {
                                            v0 = JSON.stringify(v);
                                            if (v0.length > 0) {
                                                remoteexecutiontags[k0] = v0;
                                            }
                                        }
                                        break;
                                    case "substrate":
                                        if (v.extrinsicID) {
                                            childextrinsicID = v.extrinsicID;
                                            remoteexecutiontags[k0] = JSON.stringify(v);
                                        }
                                        break;
                                    case "decodedInput":
                                    case "decodedLogs":
                                        v0 = JSON.stringify(v);
                                        if (v0.length > 0) {
                                            remoteexecutiontags[k0] = v0;
                                        }
                                        break;
                                    default:
                                        remoteexecutiontags[k0] = v0;
                                }
                            }
                        }
                        let duration = requireWeightAtMost / 10 ** 6; // requireAtMost is in picoseconds (10^12), but spans are in microseconds thus 10^6/10^12 = /10^6
                        let remoteexecspanid = this.idhash(xcmid + "-" + i.toString()); // NOTE: in case there are multiple transacts caused by the xcm message
                        this.push_span(extrinsicID, {
                            id: remoteexecspanid,
                            traceId: traceId,
                            timestamp: ts,
                            duration: duration,
                            name: `xcvm:remoteexecution`,
                            parentId: prevspanid, // parent is the transact instruction
                            tags: remoteexecutiontags,
                            localEndpoint: {
                                serviceName: idDest
                            }
                        })
                        if (childextrinsicID) {
                            if (this.extrinsic[childextrinsicID]) {
                                // there is a child extrinsic!  so we continue to child extrinsicID.  BUT:
                                // (a) msgHash: no msgHash, so we pass null
                                // (b) destEventID: no destEventID, so we pass null
                                // (c) remoteexecspanid is PASSED so the "transact" span is the parent of the child extrinsic
                                // (d) destChainID: we are on the same chain still with this remote execution
                                console.log("***** REMOTE EXECUTION CHILD DATA with XCM data", remoteexecspanid, destChainID);
                                await this.submitleg(extrinsicID, this.extrinsic[childextrinsicID], null, null, remoteexecspanid, chainIDDest);
                            } else {
                                console.log("REMOTE EXECUTION CHILD DATA, but not XCM");
                            }
                        } else {
                            console.log("REMOTE EXECUTION NO CHILD data");
                        }

                        ts += duration;
                        ts++;
                    }

                    if (childhex.length > 0) {
                        let childxcm = this.find_xcm_by_hex(childhex, xcm.blockTS);
                        if (childxcm) {
                            if (params.dest) {
                                let destChainID = this.dest_to_chainID(params.dest, xcm.relayChain);
                                if (destChainID) {
                                    // RECURSION: we found a new dest and the next leg is not an extrinsic, but we link all tracing to a single extrinsicID
                                    let childdest = this.find_dest(childxcm.msgHash, childxcm.sentAt);
                                    let childdestEventID = null
                                    if (childdest) {
                                        childdestEventID = childdest.eventID;
                                        //console.log("CHILDDEST", childxcm.msgHash, childdestEventID, childdest);
                                    }
                                    await this.submitleg(extrinsicID, null, childxcm.msgHash, childdestEventID, spanid, destChainID);
                                } else {
                                    console.log("----- DEST UNK0", params)
                                }
                            } else {
                                console.log("----- DEST UNK1", params)
                            }

                        }
                    }

                }
            }

        } else {
            console.log("Missing", msgHash);
            process.exit(0);
        }
        if (destEventID && this.dest[destEventID]) {
            let dest = this.dest[destEventID];
            let destid = this.idhash(destEventID);
            let desttags = {}
            let idDest = "destination";
            let [_chainIDDest, _idDest] = this.getNameByChainID(dest.chainIDDest)
            if (_idDest) idDest = _idDest;
            for (const [k, v] of Object.entries(dest)) {
                switch (k) {
                    case "chainIDDest":
                        break;
                    case "method":
                    case "pallet":
                        //case "msgHash":
                    case "xcmSymbol":
                    case "relayChain":
                    case "xcmInteriorKey":
                    case "sentAt":
                        break;
                    case "amountReceived":
                        desttags[k.toString()] = v.toString();

                        let p = await this.computePriceUSD({
                            symbol: dest.xcmSymbol,
                            relayChain: dest.relayChain,
                            ts: dest.destTS
                        });
                        if (p) {
                            desttags[`amountReceivedRaw`] = dest.amountReceived.toString();
                            desttags[`amountReceived`] = `${dest.amountReceived/10**p.assetInfo.decimals} ${dest.xcmSymbol}`;
                            desttags["amountReceivedUSD"] = (p.priceUSD * dest.amountReceived / 10 ** p.assetInfo.decimals).toString();
                            if (p.priceUSD) {
                                desttags["priceUSD"] = p.priceUSD.toString();
                            }
                        } else {
                            console.log("miss computePriceUSD lookup", dest.xcmSymbol, dest.relayChain, dest.xcmInteriorKey);
                        }
                        break;
                    case "blockNumberDest":
                        desttags["blockNumber"] = v.toString();
                        desttags["blockNumberURL"] = `https://polkaholic.io/block/${idDest}/${v.toString()}`
                        break;
                    default:
                        if (k && v) {
                            desttags[k.toString()] = v.toString();
                        }
                }
            }
            let dest_eventName = `${dest.pallet}:${dest.method}`;
            this.push_span(extrinsicID, {
                id: destid,
                parentId: prevspanid,
                traceId: traceId,
                timestamp: dest.destTS * 1000000,
                duration: 1000000,
                name: dest_eventName,
                tags: desttags,
                localEndpoint: {
                    serviceName: idDest
                }
            })
        }
        return traceId;
    }

    get_instruction_opcode_params(instruction) {
        for (const opcode of Object.keys(instruction)) {
            return [opcode, instruction[opcode]]
        }
        return [null, null];
    }
    compute_inclusion(childhex, c) {
        //console.log("compute_inclusion", childhex, c);
        // cnt0 = # of elements of childhex in fp1
        let cnt0 = 0;
        for (let i = 0; i < childhex.length; i++) {
            for (let j = 0; j < c.length; j++) {
                if (c[j].hex == childhex[i]) {
                    cnt0++;
                }
            }
        }
        return (cnt0 == childhex.length);

    }
    find_xcm_by_hex(childhex, parentTS) {
        // given the parentTS
        for (const msgHash of Object.keys(this.xcm)) {
            if (this.xcm[msgHash].instructions) {
                if (this.compute_inclusion(childhex, this.xcm[msgHash].instructions)) {
                    return (this.xcm[msgHash]);
                }
            } else {
                console.log("find_xcm_by_hex - MISSING INST", msgHash);
            }
        }
        return (null);

    }

    push_span(extrinsicID, span) {
        if (this.spans[extrinsicID] == undefined) {
            this.spans[extrinsicID] = [];
        }
        this.spans[extrinsicID].push(span);
    }

    dump() {
        console.log("extrinsics", Object.keys(this.extrinsic).length)
        console.log("xcm", Object.keys(this.xcm).length)
        console.log("remoteexecution", Object.keys(this.remoteexecution).length)
        console.log("dest", Object.keys(this.dest).length)
    }

    find_dest(msgHash, sentAt = 0) {
        for (const eventID of Object.keys(this.dest)) {
            let diff = this.dest[eventID].sentAt - sentAt;
            if (this.dest[eventID].msgHash == msgHash && diff >= 0 && diff <= 6) {
                return (this.dest[eventID]);
            }
        }
        return (null);
    }

    find_dest_extrinsic(e) {
        let cand = [];
        for (const eventID of Object.keys(this.dest)) {
            let d = this.dest[eventID];
            let diff = d.sentAt - e.sentAt;
            if (e.destAddress == d.fromAddress && e.xcmInteriorKey == d.xcmInteriorKey && (diff >= 0 && diff <= 6)) {
                cand.push(d);
            }
        }
        if (cand.length == 1) {
            //console.log("SINGLE", e, cand[0])
            return (cand[0]);
        }
        if (cand.length > 1) {
            console.log("MULTIPLE", e, cand)
        }
        return null;
    }

    async match() {
        // for all the extrinsics that have msgHash
        for (const extrinsicID of Object.keys(this.extrinsic)) {
            let e = this.extrinsic[extrinsicID];
            let traceID = null;

            if (e.incomplete == 1) {
                //console.log("0 extrinsic incomplete.. skip emit span with event");
            } else if (e.msgHash && this.xcm[e.msgHash]) {
                // we can link the extrinsic to a message so:
                let dest = this.find_dest(e.msgHash, e.sentAt);
                if (dest) {
                    traceID = await this.submitleg(e.extrinsicID, this.extrinsic[extrinsicID], e.msgHash, dest.eventID)
                    // 123 extrinsic+xcm+dest span 3001855-2 0x80436201761cb8f6df1714deb2ba1156881911a24ed42a07b2d6859ba55b365e 22092-1816245-1-8 https://xcmscan.polkaholic.io/trace/1c530049b0f7892c?uiEmbed=v0
                    console.log("123 extrinsic+xcm+dest leg", e.extrinsicID, e.msgHash, dest.eventID, `https://xcmscan.polkaholic.io/trace/${traceID}?uiEmbed=v0`);
                } else {
                    // don't really need dest anymore.
                    console.log("12 extrinsic+xcm span only, no dest", e.extrinsicID, e.msgHash);
                    traceID = await this.submitleg(e.extrinsicID, this.extrinsic[extrinsicID], e.msgHash, null)

                }
            } else {
                // no messagehash in extrinsic, find dest by 
                let dest = this.find_dest_extrinsic(e);
                if (dest && this.xcm[dest.msgHash] != undefined) {
                    e.msgHash = dest.msgHash;
                    traceID = await this.submitleg(e.extrinsicID, this.extrinsic[extrinsicID], e.msgHash, dest.eventID)
                    console.log("123 extrinsic+xcm+dest leg (without ext msgHash)", e.extrinsicID, dest.msgHash, dest.eventID, `https://xcmscan.polkaholic.io/trace/${traceID}?uiEmbed=v0`);

                } else {
                    //console.log("extrinsic sentAt / beneficiaries dest match required");
                }
            }
            if (e.incomplete == 0) {
                let spans = this.spans[extrinsicID];
                let endpoint = "http://efinity-internal.polkaholic.io:9411"
                let cmd = `curl -X POST ${endpoint} -H 'Content-Type: application/json' -d '${JSON.stringify(spans, null, 4)}'`
                if (spans) {
                    console.log(cmd);

                    const {
                        stdout,
                        stderr
                    } = await exec(cmd, {
                        maxBuffer: 1024 * 64000
                    });
                    if (traceID) {
                        this.batchedSQL.push(`update xcmtransfer set traceID = '${traceID}' where extrinsicID='${extrinsicID}'`)
                        this.update_batchedSQL();
                    }
                } else {
                    console.log("NO SPANS");
                }
            } else {
                console.log("INCOMPLETE");
            }
        }

    }

    receiveMsg(msg, lookbackSeconds = 3600) {
        let recursiveInstructions = [
            ["isTransferReserveAsset", "asTransferReserveAsset"],
            ["isDepositReserveAsset", "asDepositReserveAsset"],
            ["isInitiateReserveWithdraw", "asInitiateReserveWithdraw"],
            ["isInitiateTeleport", "asInitiateTeleport"],
            ["isExchangeAsset", "asExchangeAsset"]
        ];
        let startTS = this.getCurrentTS() - lookbackSeconds;
        switch (msg.type) {
            case "xcmtransfer":
                let ext = msg.msg;
                let extrinsicID = ext.extrinsicID;
                if (this.extrinsic[extrinsicID] || (ext.sourceTS < startTS)) return;
                this.extrinsic[extrinsicID] = ext;
                break;
            case "xcmmessage":
                let xcm = msg.msg;
                if (this.xcm[xcm.msgHash] || xcm.blockTS < startTS) return;
                this.xcm[xcm.msgHash] = xcm
                var o = this.api.registry.createType('XcmVersionedXcm', xcm.msgHex)
                xcm.instructions = [];
                if (o.isV2) {
                    for (let i = 0; i < o.asV2.length; i++) {
                        let inst = o.asV2[i];
                        let instruction = {
                            instruction: inst,
                            hex: inst.toHex(),
                            childinstruction: [],
                            childhex: []
                        }
                        xcm.instructions.push(instruction);
                    }
                } else if (o.isV1) {
                    let inst = o.asV1;
                    xcm.instructions.push({
                        instruction: inst,
                        hex: inst.toHex(),
                        childinstruction: [],
                        childhex: []
                    })
                }
                for (let i = 0; i < xcm.instructions.length; i++) {
                    // for all the instructions in the message, see if they could exhibit recursive
                    let instruction = xcm.instructions[i];
                    let inst = instruction.instruction;
                    for (let j = 0; j < recursiveInstructions.length; j++) {
                        let is = recursiveInstructions[j][0];
                        let as = recursiveInstructions[j][1];
                        if (inst[is]) { // ok, this instruction could exhibit recursion
                            let o2 = inst[as];
                            if (o2.xcm != undefined) { // ok, this instruction actually does exhibit recursion, containing one or more of "xcm" messages
                                // for each of the "child" instructions within "xcm", store the hex 
                                for (let k = 0; k < o2.xcm.length; k++) {
                                    instruction.childinstruction.push(o2.xcm[k]);
                                    instruction.childhex.push(o2.xcm[k].toHex());
                                }
                            }
                        }
                    }
                }
                break;
            case "xcmtransferdestcandidate":
                let dest = msg.msg;
                if (this.dest[dest.eventID] || (dest.destTS < startTS)) return;
                this.dest[dest.eventID] = dest
                break;
            case "remoteExecution":
                let remoteexecution = msg.msg;
                this.remoteexecution[remoteexecution.msgHash] = remoteexecution
                break;
        }
    }
}

async function main() {
    let tracefn = "/root/xcmscan.log";
    process.argv.forEach(function(val, index, array) {
        if (index == 2 && val.length > 0) {
            tracefn = val;
        }
    });

    let tracer = new XCMTracer();
    await tracer.assetManagerInit();
    let chain = await tracer.getChain(0);
    await tracer.setupAPI(chain);
    let lookbackSeconds = 300;

    try {
        const rl = readline.createInterface({
            input: fs.createReadStream(tracefn),
            crlfDelay: Infinity
        });

        rl.on('line', (line) => {
            tracer.receiveMsg(JSON.parse(line), lookbackSeconds);
        });
        try {
            await events.once(rl, 'close');
            tracer.dump()
            await tracer.match()
        } catch (e) {
            console.log(e);
        }

    } catch (err) {
        console.error(err);
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });
